### ISSUE TITLE
out of memory error

### ISSUE THREAD

**Issue by Gsuz** [blockworks-foundation/liquidator-v3#1]
It keeps trying to liquidate the same account and eventually runs out of memory with the following error: 

Perps:
Market: Base Pos / Quote Pos / Unsettled Funding / Health
MNGO-PERP: 0.0000 / 0.0000 / 0.0000 / 0.0000
BTC-PERP: 0.0000 / 0.0000 / 0.0000 / 0.0000
ETH-PERP: 0.0000 / 0.0000 / 0.0000 / 0.0000
SOL-PERP: 0.0000 / 0.0000 / 0.0000 / 0.0000
SRM-PERP: 0.0000 / 0.0000 / 0.0000 / 0.0000
RAY-PERP: 0.0000 / 0.0000 / 0.0000 / 0.0000
FTT-PERP: 0.0000 / 0.0000 / 0.0000 / 0.0000
ADA-PERP: 0.0000 / 0.0000 / 0.0000 / 0.0000
Started awaiting confirmation for 56CCRHz99auuEuEKovEV3AAvBoT9nsFyZrxCqp1mFWVHreF4DWDGobNQwRGgxuj9p37Z66pXt8Q3cXieHLt35JUX size: 483
Mon, 15 Nov 2021 11:39:31 GMT  sending tx  56CCRHz99auuEuEKovEV3AAvBoT9nsFyZrxCqp1mFWVHreF4DWDGobNQwRGgxuj9p37Z66pXt8Q3cXieHLt35JUX
Liquidated account 75Zbdkoh7ym9zeYe5Zgukfe8PHHo3EFgrsy3bqapoyHB
Refreshing accounts...
Sick account 75Zbdkoh7ym9zeYe5Zgukfe8PHHo3EFgrsy3bqapoyHB health ratio: -99.76381300873988777766
MangoAccount 75Zbdkoh7ym9zeYe5Zgukfe8PHHo3EFgrsy3bqapoyHB
Owner: DLEeT1kZ6q5kHPsSyAYz67SGDn2qHPsVt1HaGDsKc8L
Maint Health Ratio: -99.7638
Maint Health: -17.2531
Init Health: -18.8298
Equity: 0.3256
isBankrupt: false
beingLiquidated: true
Spot:
Token: Net Balance / Base In Orders / Quote In Orders
BTC: -0.0000 / 0.0000 / 0.0000
SOL: 0.0000 / 0.0000 / 0.0000
Perps:
Market: Base Pos / Quote Pos / Unsettled Funding / Health
MNGO-PERP: 0.0000 / 0.0000 / 0.0000 / 0.0000
BTC-PERP: 0.0000 / 0.0000 / 0.0000 / 0.0000
ETH-PERP: 0.0000 / 0.0000 / 0.0000 / 0.0000
SOL-PERP: 0.0000 / 0.0000 / 0.0000 / 0.0000
SRM-PERP: 0.0000 / 0.0000 / 0.0000 / 0.0000
RAY-PERP: 0.0000 / 0.0000 / 0.0000 / 0.0000
FTT-PERP: 0.0000 / 0.0000 / 0.0000 / 0.0000
ADA-PERP: 0.0000 / 0.0000 / 0.0000 / 0.0000
Started awaiting confirmation for 5tLb1cT2fKbrrxiBYcVZ8MurCniXJZFEgaFyAaQjqoQG12Q6SB3ZNyn9CYrKS6edKQ31gh9fTTTcWVKD6qTgZ61b size: 483
Mon, 15 Nov 2021 11:39:42 GMT  sending tx  5tLb1cT2fKbrrxiBYcVZ8MurCniXJZFEgaFyAaQjqoQG12Q6SB3ZNyn9CYrKS6edKQ31gh9fTTTcWVKD6qTgZ61b
REST confirmed 5tLb1cT2fKbrrxiBYcVZ8MurCniXJZFEgaFyAaQjqoQG12Q6SB3ZNyn9CYrKS6edKQ31gh9fTTTcWVKD6qTgZ61b {
  confirmationStatus: 'processed',
  confirmations: 0,
  err: null,
  slot: 106999639,
  status: { Ok: null }
}
Liquidated account 75Zbdkoh7ym9zeYe5Zgukfe8PHHo3EFgrsy3bqapoyHB

<--- Last few GCs --->

[13604:0x130008000]   157593 ms: Scavenge (reduce) 2045.1 (2082.8) -> 2044.7 (2083.3) MB, 3.5 / 0.0 ms  (average mu = 0.315, current mu = 0.264) allocation failure 
[13604:0x130008000]   159614 ms: Mark-sweep (reduce) 2045.6 (2083.3) -> 2045.1 (2084.1) MB, 1516.9 / 0.0 ms  (+ 60.0 ms in 12 steps since start of marking, biggest step 11.8 ms, walltime since start of marking 1587 ms) (average mu = 0.273, current mu = 0.

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0x100f2f380 node::Abort() [/usr/local/bin/node]
 2: 0x100f2f508 node::errors::TryCatchScope::~TryCatchScope() [/usr/local/bin/node]
 3: 0x10107b8a4 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0x10107b838 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x101217da4 v8::internal::Heap::GarbageCollectionReasonToString(v8::internal::GarbageCollectionReason) [/usr/local/bin/node]
 6: 0x1012168e4 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
 7: 0x101221998 v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 8: 0x101221a2c v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 9: 0x1011f4e6c v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/local/bin/node]
10: 0x101527788 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
11: 0x10183158c Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/usr/local/bin/node]
12: 0x10189be18 Builtins_CreateTypedArray [/usr/local/bin/node]
13: 0x105a6288c 
14: 0x105b4d0cc 
15: 0x105b4be1c 
16: 0x1017c5cb8 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
17: 0x1017c5cb8 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
18: 0x10184c008 Builtins_ArrayMap [/usr/local/bin/node]
19: 0x1017c5cb8 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
20: 0x1017f6fac Builtins_GeneratorPrototypeNext [/usr/local/bin/node]
21: 0x1017c5cb8 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
22: 0x101877898 Builtins_PromiseFulfillReactionJob [/usr/local/bin/node]
23: 0x1017e7734 Builtins_RunMicrotasks [/usr/local/bin/node]
24: 0x1017c3984 Builtins_JSRunMicrotasksEntry [/usr/local/bin/node]
25: 0x1011a502c v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/usr/local/bin/node]
26: 0x1011a5460 v8::internal::(anonymous namespace)::InvokeWithTryCatch(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/usr/local/bin/node]
27: 0x1011a5528 v8::internal::Execution::TryRunMicrotasks(v8::internal::Isolate*, v8::internal::MicrotaskQueue*, v8::internal::MaybeHandle<v8::internal::Object>*) [/usr/local/bin/node]
28: 0x1011c81e8 v8::internal::MicrotaskQueue::RunMicrotasks(v8::internal::Isolate*) [/usr/local/bin/node]
29: 0x1011c8064 v8::internal::MicrotaskQueue::PerformCheckpoint(v8::Isolate*) [/usr/local/bin/node]
30: 0x1017c8354 Builtins_CallApiCallback [/usr/local/bin/node]
31: 0x105b1cc90 
32: 0x1017c3aac Builtins_JSEntryTrampoline [/usr/local/bin/node]
33: 0x1017c3744 Builtins_JSEntry [/usr/local/bin/node]
34: 0x1011a5064 v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/usr/local/bin/node]
35: 0x1011a46f8 v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) [/usr/local/bin/node]
36: 0x101097534 v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) [/usr/local/bin/node]
37: 0x100e7ee40 node::InternalCallbackScope::Close() [/usr/local/bin/node]
38: 0x100e7f36c node::InternalMakeCallback(node::Environment*, v8::Local<v8::Object>, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [/usr/local/bin/node]
39: 0x100e944ac node::AsyncWrap::MakeCallback(v8::Local<v8::Function>, int, v8::Local<v8::Value>*) [/usr/local/bin/node]
40: 0x100fca338 node::(anonymous namespace)::CompressionStream<node::(anonymous namespace)::ZlibContext>::AfterThreadPoolWork(int) [/usr/local/bin/node]
41: 0x1017a40f4 uv__work_done [/usr/local/bin/node]
42: 0x1017a7854 uv__async_io [/usr/local/bin/node]
43: 0x1017b9568 uv__io_poll [/usr/local/bin/node]
44: 0x1017a7ce4 uv_run [/usr/local/bin/node]
45: 0x100e7fe00 node::SpinEventLoop(node::Environment*) [/usr/local/bin/node]
46: 0x100f686c0 node::NodeMainInstance::Run(int*, node::Environment*) [/usr/local/bin/node]
47: 0x100f6838c node::NodeMainInstance::Run(node::EnvSerializeInfo const*) [/usr/local/bin/node]
48: 0x100f0134c node::Start(int, char**) [/usr/local/bin/node]
49: 0x1056f90f4 
error Command failed with signal "SIGABRT".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by riordanp** [comment]
There were two issues here. The repeated liquidation of the same account was down to a program bug which has now been resolved. As for the memory issue, you can try increasing the heap space available to the node process by starting with, for example, `NODE_OPTIONS="--max-old-space-size=4096"`.
