### ISSUE TITLE
Error Question

### ISSUE THREAD

**Issue by teehanming** [blockworks-foundation/liquidator-v3#15]
```
Started awaiting confirmation for 5G9A2K82Ni21yfePd2d1gidwu7ajjh9H7jNGB3Rtpg77cYE8nYakVJaL5cWUdVSPaVcNeBbuBh2BdKSS4CLuh5po size: 804

Failed to liquidate account 5YT87jzUhwHyKeYg1KYhJm1nr1HJ3UCZfZcFgsKB7feV: Error: Transaction failed: MangoErrorCode::NotLiquidatable; src/processor.rs:3276

Could not match OpenOrdersAccount to MangoAccount
```

What does "Could not match OpenOrdersAccount to MangoAccount" mean by this?
Is it the taker or maker account?

**Comment by riordanp** [comment]
Hi @teehanming, this line is simply a warning that the liquidator received information about an Open Orders account for which it could not find the owner Mango Account. This happens sometimes when somebody creates an account then trades spot quite quickly, leading to the updates being out of order.

Generally it's nothing to worry about and isn't related to the prior failed liquidation.
