### ISSUE TITLE
Failed to liquidate account error, this.connection.getLatestBlockhash is not a function

### ISSUE THREAD

**Issue by yongyi520** [blockworks-foundation/liquidator-v3#25]
Failed to liquidate account 2doMDoNXGoT64j7AumDR4uSgq3N37ZXZRAUCEHuZR4A1: TypeError: this.connection.getLatestBlockhash is not a function

Is this an error due to the server or from the type script?
`Failed to liquidate account 7BNrgWmyha1dVgJ6j8gFHi1Tom6Mrac4du1jp9tncDq4: TypeError: this.connection.getLatestBlockhash is not a function
    at MangoClient.<anonymous> (/Users/yii/Documents/Code/liquidator-v3/node_modules/@blockworks-foundation/mango-client/src/client.ts:236:48)`

**Comment by Aoikiseki** [comment]
@yongyi520 maybe your web3.js is out of date, try to update @solana/web3.js version, 1.4x.0 for example

**Comment by soapyp** [comment]
Hi @yongyi520, this was indeed an issue related to web3.js being outdated. I've upgraded everything now on main so try out the latest commit and see if that works better for you.

**Comment by yongyi520** [comment]
thank you everyone! @Aoikiseki @riordanp
