### ISSUE TITLE
Potential Bug in Liquidate Spot

### ISSUE THREAD

**Issue by buffalu** [blockworks-foundation/liquidator-v3#5]
Should [this](https://github.com/blockworks-foundation/liquidator-v3/blob/e2f6ea56b5727210b8c62b3ea1822c25e3325e76/src/liquidator.ts#L520) be:

```ts
shouldLiquidateSpot |= liqee.getNet(cache.rootBankCache[i], i).isNeg();
```

**Comment by dafyddd** [comment]
Yeah looks like a bug. @riordanp can you patch?

**Comment by dafyddd** [comment]
nevermind I fixed; thanks @buffalu  for pointing out the bug

**Comment by buffalu** [comment]
np!
